POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "four",
    "password": "four"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "",
    "password": ""
}