POST http://localhost:3001/api/quotes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpdmUiLCJpZCI6IjYwMzUyYjMxOTFlNjJlMGM5YjJmMTEyYiIsImlhdCI6MTYxNDE4NzgxN30.TLKmJNrjA_s32mPmz4fyIO2ZfXwFBhFs7HWwy_82_84

{
    "content": "Persistent is key to success",
    "author": "Jiro Ono",
    "vote": 0
}